version: "3.1"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: heenatalreja/jenkins-pipeline:latest
    stop_grace_period: 30s
    deploy:
      replicas: 5
      update_config:
        failure_action: rollback
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8090:8080"   
